BEGIN;
-- Company profile (synthetic demo data)
WITH new_profile AS (INSERT INTO company_profile (name, description, country, website, notes, source_notes) VALUES ('Baltic Industrial Works Ltd.', 'Fabrication and machining of steel components for power and industrial plants.', 'Poland', 'https://example.com', 'Synthetic demo profile for readiness checks.', 'Synthetic data; replace with real company profile.') RETURNING id) INSERT INTO company_capability (profile_id, capability, capacity, certification, source_notes) SELECT new_profile.id, t.capability, t.capacity, t.certification, t.source_notes FROM new_profile CROSS JOIN (VALUES ('Pressure parts fabrication (boilers, superheaters)', 'Up to 12,000 kg assemblies; 45 t/month', 'UDT approval; ISO 3834-2', 'Synthetic demo data'), ('Mechanical drives (gearboxes, reducers)', 'Custom and batch production', 'ISO 9001', 'Synthetic demo data'), ('Field installation and commissioning', 'On-site teams across Poland', 'Welding EN 287-1', 'Synthetic demo data')) AS t(capability, capacity, certification, source_notes);

-- Tenders
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_11005-2018_EN', E'ted_11005-2018_EN.pdf', E'Wyposażenie pracowni elektrycznej w elementy inteligentnego domu KNX (w ramach projektu „Dostosowanie infrastruktury placówek edukacyjnych Powiatu Jasielskiego...', NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_16879-2018_EN', E'ted_16879-2018_EN.pdf', NULL, NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_17790-2018_EN', E'ted_17790-2018_EN.pdf', E'System ultra-wysokiej próżni (ang. Ultra-High Vacuum - UHV) dla stacji badawczej PHELIX Lot No: 1', NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_22593-2018_EN', E'ted_22593-2018_EN.pdf', NULL, NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_27300-2018_EN', E'ted_27300-2018_EN.pdf', NULL, NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_28043-2018_EN', E'ted_28043-2018_EN.pdf', E'Pakiet 1: Wyposażenie pracowni instalacyjnych Lot No: 1', NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_36520-2018_EN', E'ted_36520-2018_EN.pdf', NULL, NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_43628-2018_EN', E'ted_43628-2018_EN.pdf', E'Dostawa, instalacja i uruchomienie powiatowego systemu ostrzegania i alarmowania ludności na terenie powiatu kartuskiego. Lot No: 1', NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_52967-2018_EN', E'ted_52967-2018_EN.pdf', E'Dostawa wirówki laboratoryjnej wraz z wyposażeniem dla Wydziału Chemii Lot No: 1', NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_5789-2018_EN', E'ted_5789-2018_EN.pdf', E'Zadanie nr 1 - Reduktor napędu Lot No: 1', NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_5791-2018_EN', E'ted_5791-2018_EN.pdf', NULL, NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_5835-2018_EN', E'ted_5835-2018_EN.pdf', NULL, NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_58389-2018_EN', E'ted_58389-2018_EN.pdf', E'Dostawa i montaż kolektorów słonecznych na terenie Gminy Jastrzębia Lot No: 1', NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_60456-2018_EN', E'ted_60456-2018_EN.pdf', E'Część 1 - Części zamienne do chwytaków hydraulicznych typ PH6-8000-0 Lot No: 1', NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_63785-2018_EN', E'ted_63785-2018_EN.pdf', NULL, NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_67162-2018_EN', E'ted_67162-2018_EN.pdf', E'Dostawa i montaż instalacji solarnych w budynkach mieszkalnych na terenie Gminy Sosnówka Lot No: 1', NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_70675-2018_EN', E'ted_70675-2018_EN.pdf', NULL, NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_70680-2018_EN', E'ted_70680-2018_EN.pdf', E'Remont kapitalny armatury i rurociągów turbozespołu TG-1 w PGE Energia Ciepła S.A. oddział w Krakowie. Lot No: 1', NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_72652-2018_EN', E'ted_72652-2018_EN.pdf', E'Armatura Lot No: 1', NULL, E'Seeded from tender metadata only (no PDF content stored).');
INSERT INTO tenders (tender_id, source_file, primary_title, summary, notes) VALUES (E'ted_812-2018_EN', E'ted_812-2018_EN.pdf', NULL, NULL, E'Seeded from tender metadata only (no PDF content stored).');

-- Company delivery history (synthetic demo data)
INSERT INTO company_delivery (tender_id, title, customer, delivered_at, value, currency, scope, evidence, source_notes) VALUES (E'ted_5789-2018_EN', E'Gearbox assemblies for conveyor drives', E'PGG S.A. (synthetic)', E'2023-05-20', 450000, E'PLN', E'Production and delivery of industrial gearboxes for mining conveyors.', E'Reference letter (synthetic)', E'Synthetic demo data');
INSERT INTO company_delivery (tender_id, title, customer, delivered_at, value, currency, scope, evidence, source_notes) VALUES (E'ted_5789-2018_EN', E'Motoreducers for heavy-duty handling line', E'Industrial client (synthetic)', E'2022-09-10', 320000, E'PLN', E'Batch delivery of motoreducers with custom ratios.', E'Delivery acceptance protocol (synthetic)', E'Synthetic demo data');
INSERT INTO company_delivery (tender_id, title, customer, delivered_at, value, currency, scope, evidence, source_notes) VALUES (E'ted_812-2018_EN', E'Boiler superheater pressure parts', E'Power plant operator (synthetic)', E'2021-03-15', 680000, E'PLN', E'Fabrication of pressure parts for OP 230 boilers.', E'Contract and acceptance note (synthetic)', E'Synthetic demo data');
COMMIT;
